프로젝트 수행 방법 :   
주 데이터는 cars.csv이며, 보조자료로 brand.csv도 준비되어있으니 함께 활용해보세요. 이번 프로젝트에서는  
1) "중고차 가격 예측 모델"을 가정하여 데이터를 준비해볼 수도 있고,   
2) "중고차 특성에 따른 클러스터링"을 가정하여 데이터를 준비해볼 수도 있습니다.

아직 머신러닝 알고리즘을 학습하기 전 단계이니, 배웠던 내용을 최대한 활용하여 다양하게 데이터를 변환해보세요.  
만약 이전에 배웠던 학습 내용이 익숙하지 않다면 이전 내용을 다시 한번 복습해 주세요. 🤗   
Step 1. 이것만큼은 꼭 해보세요!
프로젝트에 정답은 없습니다. 배우신 내용을 토대로 자유롭게 데이터를 정제하고 변환하되, 아래 내용만큼은 반드시 실습해봅시다.

*1) cars.csv와 brand.csv의 데이터 합치기
[힌트] cars.csv의 title 변수로부터 브랜드 데이터를 추출할 수 있습니다.

*2) 카테고리형 변수를 숫자 형태로 변환하기
[힌트] Engine, Emission Class 변수에 주목하세요!

*3) 결측치 처리하기
[힌트] Service history 변수의 결측치는 'Unknown'으로 채우고, 결측치 변수가 일정 개수 이상 포함된 데이터는 제거합니다.

*4) Scaler 활용해보기
기존 데이터의 정보 70% 이상을 가지는 수준에서 최소한의 주성분 추출 (PCA)


### Step 2. 이런것도 해볼 수 있어요!
자유롭게 실습을 해보시고, 여유가 되면 아래의 내용도 실습해보세요.

2-1) 국가별 총 브랜드 개수는?  
2-2) 상관관계가 높은 변수들이 있는지 확인해보세요.

In [1]:
# 파일 시작하기 템플릿

import sys, os
print(sys.executable)
print(os.getcwd())

from pathlib import Path
print(Path().resolve())

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

d:\011.DA_Projects\02.DA_PJT_1\.venv\Scripts\python.exe
d:\011.DA_Projects\02.DA_PJT_1\58.PJT_2nd_car
D:\011.DA_Projects\02.DA_PJT_1\58.PJT_2nd_car

In [2]:
# 메일 파일 열기

pd.read_csv(r"D:\011.DA_Projects\02.DA_PJT_1\58.PJT_2nd_car\cars_main_work1.csv")

,title,Price,Mileage(miles),Registration_Year,Previous Owners,Fuel type,Body type,Engine,Gearbox,Doors,Seats,Emission Class,Service history
0,SKODA FABIA,6900,70189,2016,3.0,Diesel,Hatchback,1.4L,Manual,5.0,5.0,Euro 6,NaN
1,VAUXHALL CORSA,1495,88585,2008,4.0,Petrol,Hatchback,1.2L,Manual,3.0,5.0,Euro 4,Full
2,HYUNDAI I30,949,137000,2011,NaN,Petrol,Hatchback,1.4L,Manual,5.0,5.0,Euro 5,NaN
3,MINI HATCH,2395,96731,2010,5.0,Petrol,Hatchback,1.4L,Manual,3.0,4.0,Euro 4,Full
4,VAUXHALL CORSA,1000,85000,2013,NaN,Diesel,Hatchback,1.3L,Manual,5.0,5.0,Euro 5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3682,RENAULT MEGANE,1395,76202,2006,4.0,Petrol,Hatchback,1.6L,Manual,5.0,5.0,Euro 4,NaN
3683,AUDI A4,6990,119000,2012,NaN,Petrol,Saloon,2.0L,Manual,4.0,5.0,Euro 5,NaN
3684,BMW 3 SERIES,3995,139000,2013,NaN,Diesel,Saloon,2.0L,Manual,4.0,5.0,Euro 5,NaN
3685,HONDA ACCORD,1390,179190,2007,NaN,Diesel,Estate,2.2L,Manual,5.0,5.0,Euro 4,Full
3686,VAUXHALL CORSA,2000,82160,2013,7.0,Petrol,Hatchback,1.2L,Manual,5.0,5.0,Euro 5,NaN

In [3]:
# 파일이름 df1으로 저장 후 살펴보기

df1 = pd.read_csv(r"D:\011.DA_Projects\02.DA_PJT_1\58.PJT_2nd_car\cars_main_work1.csv")
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 3687 entries, 0 to 3686
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              3687 non-null   str
 1   Price              3687 non-null   int64
 2   Mileage(miles)     3687 non-null   int64
 3   Registration_Year  3687 non-null   int64
 4   Previous Owners    2276 non-null   float64
 5   Fuel type          3687 non-null   str
 6   Body type          3687 non-null   str
 7   Engine             3642 non-null   str
 8   Gearbox            3687 non-null   str
 9   Doors              3662 non-null   float64
 10  Seats              3652 non-null   float64
 11  Emission Class     3600 non-null   str
 12  Service history    540 non-null    str
dtypes: float64(3), int64(3), str(7)
memory usage: 374.6 KB

In [4]:
# 결측치 확인 

df1.isna().sum()

title                   0
Price                   0
Mileage(miles)          0
Registration_Year       0
Previous Owners      1411
Fuel type               0
Body type               0
Engine                 45
Gearbox                 0
Doors                  25
Seats                  35
Emission Class         87
Service history      3147
dtype: int64

In [5]:
# sub 파일 열어서 확인하기

pd.read_csv(r"D:\011.DA_Projects\02.DA_PJT_1\58.PJT_2nd_car\brand_sub_work1.csv")

            title         country
0           skoda  Czech Republic
1        vauxhall  United Kingdom
2         hyundai     South Korea
3            mini  United Kingdom
4            ford   United States
5           volvo          Sweden
6         peugeot          France
7             bmw         Germany
8         citroen          France
9   mercedes-benz         Germany
10          mazda           Japan
11           saab          Sweden
12     volkswagen         Germany
13          honda           Japan
14             mg  United Kingdom
15         toyota           Japan
16           seat           Spain
17         nissan           Japan
18           alfa           Italy
19        renault          France
20            kia     South Korea
21         proton        Malaysia
22           fiat           Italy
23           audi         Germany
24     mitsubishi           Japan
25          lexus           Japan
26           land  United Kingdom
27      chevrolet   United States
28         suzuki           Japan
29          dacia         Romania
30       daihatsu           Japan
31           jeep   United States
32         jaguar  United Kingdom
33       chrysler   United States
34          rover  United Kingdom
35             ds          France
36         daewoo     South Korea
37          dodge   United States
38        porsche         Germany
39         subaru           Japan
40       infiniti           Japan
41         abarth           Italy
42          smart         Germany
43         marcos  United Kingdom
44       maserati           Italy
45      ssangyong     South Korea
46        lagonda  United Kingdom
47          isuzu           Japan

In [6]:
# sub 파일 열어서 확인 후 df2로 저장하기

df2 = pd.read_csv(r"D:\011.DA_Projects\02.DA_PJT_1\58.PJT_2nd_car\brand_sub_work1.csv")

In [7]:
# 기본 정보 보기

df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    48 non-null     str
 1   country  48 non-null     str
dtypes: str(2)
memory usage: 900.0 bytes

### 1 데이터 합치기

In [8]:
# 1-1 두 데이터프레임을 합치기

combined_cars = pd.concat([df1, df2])
combined_cars.info()
combined_cars.head(10)

<class 'pandas.DataFrame'>
Index: 3735 entries, 0 to 47
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              3735 non-null   str
 1   Price              3687 non-null   float64
 2   Mileage(miles)     3687 non-null   float64
 3   Registration_Year  3687 non-null   float64
 4   Previous Owners    2276 non-null   float64
 5   Fuel type          3687 non-null   str
 6   Body type          3687 non-null   str
 7   Engine             3642 non-null   str
 8   Gearbox            3687 non-null   str
 9   Doors              3662 non-null   float64
 10  Seats              3652 non-null   float64
 11  Emission Class     3600 non-null   str
 12  Service history    540 non-null    str
 13  country            48 non-null     str
dtypes: float64(6), str(8)
memory usage: 437.7 KB

,title,Price,Mileage(miles),Registration_Year,Previous Owners,Fuel type,Body type,Engine,Gearbox,Doors,Seats,Emission Class,Service history,country
0,SKODA FABIA,6900.0,70189.0,2016.0,3.0,Diesel,Hatchback,1.4L,Manual,5.0,5.0,Euro 6,NaN,NaN
1,VAUXHALL CORSA,1495.0,88585.0,2008.0,4.0,Petrol,Hatchback,1.2L,Manual,3.0,5.0,Euro 4,Full,NaN
2,HYUNDAI I30,949.0,137000.0,2011.0,NaN,Petrol,Hatchback,1.4L,Manual,5.0,5.0,Euro 5,NaN,NaN
3,MINI HATCH,2395.0,96731.0,2010.0,5.0,Petrol,Hatchback,1.4L,Manual,3.0,4.0,Euro 4,Full,NaN
4,VAUXHALL CORSA,1000.0,85000.0,2013.0,NaN,Diesel,Hatchback,1.3L,Manual,5.0,5.0,Euro 5,NaN,NaN
5,HYUNDAI COUPE,800.0,124196.0,2007.0,3.0,Petrol,Coupe,2.0L,Manual,3.0,4.0,Euro 4,NaN,NaN
6,FORD FOCUS,798.0,140599.0,2008.0,NaN,Petrol,Hatchback,1.6L,Manual,5.0,5.0,Euro 4,NaN,NaN
7,VAUXHALL CORSA,1995.0,90000.0,2009.0,NaN,Petrol,Hatchback,1.2L,Manual,3.0,5.0,Euro 4,NaN,NaN
8,VOLVO 740,750.0,225318.0,2025.0,NaN,Petrol,Estate,2.3L,Automatic,5.0,NaN,NaN,NaN,NaN
9,PEUGEOT 207,1299.0,87000.0,2008.0,5.0,Diesel,Hatchback,1.6L,Manual,5.0,5.0,Euro 4,NaN,NaN

In [9]:
# 1-2 카테고리형(Engine, Emission Class) → 숫자로 바꾸기 

# Engine: "1.6L" -> 1.6
df1["Engine"] = df1["Engine"].astype(str).str.replace("L", "", regex=False)
df1["Engine"] = pd.to_numeric(df1["Engine"], errors="coerce")

# Emission Class: "Euro 6" -> 6
df1["Emission Class"] = df1["Emission Class"].astype(str).str.extract(r"(\d+)")
df1["Emission Class"] = pd.to_numeric(df1["Emission Class"], errors="coerce")
df1

,title,Price,Mileage(miles),Registration_Year,Previous Owners,Fuel type,Body type,Engine,Gearbox,Doors,Seats,Emission Class,Service history
0,SKODA FABIA,6900,70189,2016,3.0,Diesel,Hatchback,1.4,Manual,5.0,5.0,6.0,NaN
1,VAUXHALL CORSA,1495,88585,2008,4.0,Petrol,Hatchback,1.2,Manual,3.0,5.0,4.0,Full
2,HYUNDAI I30,949,137000,2011,NaN,Petrol,Hatchback,1.4,Manual,5.0,5.0,5.0,NaN
3,MINI HATCH,2395,96731,2010,5.0,Petrol,Hatchback,1.4,Manual,3.0,4.0,4.0,Full
4,VAUXHALL CORSA,1000,85000,2013,NaN,Diesel,Hatchback,1.3,Manual,5.0,5.0,5.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3682,RENAULT MEGANE,1395,76202,2006,4.0,Petrol,Hatchback,1.6,Manual,5.0,5.0,4.0,NaN
3683,AUDI A4,6990,119000,2012,NaN,Petrol,Saloon,2.0,Manual,4.0,5.0,5.0,NaN
3684,BMW 3 SERIES,3995,139000,2013,NaN,Diesel,Saloon,2.0,Manual,4.0,5.0,5.0,NaN
3685,HONDA ACCORD,1390,179190,2007,NaN,Diesel,Estate,2.2,Manual,5.0,5.0,4.0,Full
3686,VAUXHALL CORSA,2000,82160,2013,7.0,Petrol,Hatchback,1.2,Manual,5.0,5.0,5.0,NaN

In [10]:
# 1-3 Service history 결측치 채우기

df1["Service history"] = df1["Service history"].fillna("Unknown")

# 확인
df1.isna().sum()

title                   0
Price                   0
Mileage(miles)          0
Registration_Year       0
Previous Owners      1411
Fuel type               0
Body type               0
Engine                 45
Gearbox                 0
Doors                  25
Seats                  35
Emission Class         87
Service history         0
dtype: int64

In [ ]:
# 1-3 결측치 처리

# Service history 결측치 'Unknown'으로 채우기
df1["Service history"] = df1["Service history"].fillna("Unknown")

# 결측값 1411인 'Previous Owners' column을 삭제
df1 = df1.drop('Previous Owners', axis =1)

# 확인
df1.isna().sum()

title                 0
Price                 0
Mileage(miles)        0
Registration_Year     0
Fuel type             0
Body type             0
Engine               45
Gearbox               0
Doors                25
Seats                35
Emission Class       87
Service history       0
dtype: int64

In [12]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# 1) 숫자 컬럼만 가져오기
X = df1.select_dtypes(include=["number"]).copy()

# 2) inf -> NaN
X = X.replace([np.inf, -np.inf], np.nan)

# 3) NaN 채우기 (행이 0개 되는 것 방지)
X = X.fillna(X.mean())

# 4) 혹시 평균으로도 못 채운 컬럼(전부 NaN)이 있으면 그 컬럼 삭제
X = X.dropna(axis=1)

print("X shape:", X.shape)   # 여기서 (0, ?)면 df1 자체가 비어있는 상태

# 5) 표준화 + PCA
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=0.70)
X_pca = pca.fit_transform(X_scaled)

print("주성분 개수:", pca.n_components_)
print("설명력 합:", pca.explained_variance_ratio_.sum())

X shape: (3687, 7)
주성분 개수: 3
설명력 합: 0.783365041320241